<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/vendors.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/forms/icheck/icheck.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/extensions/jquery.steps.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/pickers/dateTime/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/core/app-menu.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/core/app.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/forms/checkbox-radio.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/forms/extended/typeahead/bloodhound.min.js"></script>
<script src="<?php echo BASE_DIR;?>/_libs/js/bootstrap3-typeahead.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/forms/extended/inputmask/jquery.inputmask.bundle.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/forms/extended/form-inputmask.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/forms/repeater/jquery.repeater.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/forms/form-repeater.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/extensions/sweetalert2.all.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/ui/headroom.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/core/main.js"></script> <!-- to-Top -->
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
<script src="<?php echo BASE_DIR;?>/_libs/js/script.js?v<?php echo rand(); ?>"></script>     <!-- script master -->
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/forms/extended/maxlength/bootstrap-maxlength.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/forms/extended/form-maxlength.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/navs/navs.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/core/libraries/jquery_ui/jquery-ui.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/extensions/sweetalert.min.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/js/scripts/extensions/sweet-alerts.js"></script>
<script src="<?php echo BASE_DIR;?>/theme/app-assets/vendors/js/timeline/horizontal-timeline.js"></script>
